### ISSUE TITLE
Last commit broke interface

### ISSUE THREAD

**Issue by f3bruary** [theroyalstudent/layered#10]
commit 81b00a1fe894cfcd1233bb8bb8b4fa8e1ca0d846

http://i.imgur.com/MugeWTx.png

**Comment by runbiscuit** [comment]
Don't see it broken here, mind providing me with screenshots of `Inspect > Console`? Thanks.

**Comment by f3bruary** [comment]
ah I see there were some files missing. Did a fresh git clone, and copied the files over and it's working now. Thanks.
