### ISSUE TITLE
UI don't conforme to what expected

### ISSUE THREAD

**Issue by gfelot** [theroyalstudent/layered#17]
I found your work here : 
https://forum.transmissionbt.com/viewtopic.php?f=8&t=17704
And I don't have the same UI.

Instead I got this : 
http://imgur.com/M2TN1pH

If I have time I'm gonna look too. But you know your code better than me.

**Comment by runbiscuit** [comment]
Hey there,

This is what I have:
http://i.imgur.com/s506Bpi.png

It seems that the fonts aren't loading. Mind opening 'Inspect Element > Console' and making a screenshot of the output?

Everything seems to be working fine on my server.

Thanks!

**Comment by gfelot** [comment]
Yep it's a font problem.

http://imgur.com/Lp694Gw

**Comment by runbiscuit** [comment]
Try cloning again. Or, you can download the one in the "Releases" section. Everything seems to be intact in the repository.

How did you get the repository from the upstream?

Here are the fonts folder:
http://i.imgur.com/dTeekky.png
http://i.imgur.com/gGfK2YR.png

**Comment by runbiscuit** [comment]
Closing this issue, since no additional feedback has been given. The code is fine.
