### ISSUE TITLE
Feature request : Status bar.

### ISSUE THREAD

**Issue by cleme29** [theroyalstudent/layered#18]
Hi !
Could you add a bar at the bottom of the page that shows an overview of actual upload/download speed, disk usage, and others stats.. like do Transmission Remote GUI, it would be really nice if you can !

Thanks !

**Comment by cleme29** [comment]
I'm just blind, I didn't see it at the top right.. :D

**Comment by runbiscuit** [comment]
@BloodMan29 Haha, I was a little confused, thought that the functionality was just right there and decided to wait for you to realise that :p Have fun with Layered!
