### ISSUE TITLE
Missing Fonts

### ISSUE THREAD

**Issue by Joomla12** [theroyalstudent/layered#19]
It seems Unicode characters are missing for the left and right buttons, stop and play buttons, and the open and settings buttons. What font was used for these?

http://i.imgur.com/I4x9FRp.png

**Comment by runbiscuit** [comment]
I have re-cloned the interface on my seedbox, and it's working fine, with cache disabled - for some reason a few people have an issue with this - try cloning again!

![](http://i.imgur.com/kgW77Sx.png)

See issue #17 and #10.

(do give me a feedback or this will be closed within 48 hours)

**Comment by Joomla12** [comment]
Nope, still happening after re-cloning. I even wiped the last folder so I could start fresh. I do have some caching options on in my Apache config. I'll try disabling those and see if it fixes the problem. Also, here's a screen shot of the developer console.

http://i.imgur.com/zbzGSaf.png

Edit: I tried using the release instead, but it's giving me the same issue. I also disabled the caching options in my Apache configuration, but that did nothing. Googling around suggests the font files got corrupted somehow, but I have no idea how.

**Comment by Joomla12** [comment]
Alright, I fixed it. The issue is with "icons.css". I dunno if the font files in the repo are corrupted or what, but I submitted a pull request.
Edit: I've found the issue. The font path is hardcoded to "/transmission/web/path/to/fonts/", whereas I use "/client/" in Transmission's settings. This makes sense now. Anyway, I'm gonna close the issue since I've fixed it.
