### ISSUE TITLE
Clicking "More Details" a Second Time Causes Close Button to Disappear

### ISSUE THREAD

**Issue by Joomla12** [theroyalstudent/layered#20]
Alright, here's a new issue. When clicking "More Details" on a torrent a second time causes the close button to disappear. The stop button also becomes nonfunctional until the page is refreshed.

**Comment by runbiscuit** [comment]
Noted, with thanks, however I do not have much time to maintain this project at all recently, but am currently learning Angular 2. Will see what I can do once I learn Angular 2 to tidy up the code and everything.

Really appreciate your effort in informing me about these issues.

**Comment by Joomla12** [comment]
Any time. It's not that big of an issue, so just take your time. I know how tedious it can be to manage a project entirely by yourself. Also, I'm fairly new to Git, so if I didn't submit my pull request properly for the last issue, I apologize.

**Comment by runbiscuit** [comment]
I'm actually pretty new to Git too, I haven't seen your pull request show up on my side (you apparently pull requested yourself?), but have seen your fork. Will do a PR either tonight or tomorrow night when I get home and have the time to do a quick test :)

Thanks for the fix - the font issue has been reported by a few users and I never knew what was wrong.

**Comment by runbiscuit** [comment]
Should be fixed now.
