### ISSUE TITLE
Tooltips not Showing of left Section

### ISSUE THREAD

**Issue by TheFruF** [theroyalstudent/layered#23]
thanks for the work - Wonderfull UI!

On the Webinterface the Toolstips (data-tooltip) are Missing for the left of the two sections. 
The Values are there in the code, but will not show
Right Section : works
![data_working](https://cloud.githubusercontent.com/assets/18738200/16108946/7fb053d8-33a6-11e6-8f87-f4defba77fd8.PNG)

Right Section : Tooltips work
![text](https://cloud.githubusercontent.com/assets/18738200/16108665/d8609b70-33a4-11e6-8047-d3ab86b9a743.png)

Left Section doenst work
![data_notworking](https://cloud.githubusercontent.com/assets/18738200/16108955/8b447116-33a6-11e6-9706-6c7ab8266653.PNG)

Left Section : No Tooltips
![notext](https://cloud.githubusercontent.com/assets/18738200/16108781/8e743c46-33a5-11e6-83cc-87fcc209e196.png)

Testet with Firefox 45 and 47 plus IE 11
FruF

**Comment by TheFruF** [comment]
Update:
If I just use one List, the Tooltips work. (so i put buttons in the right section)
So either they dont like having 2 Sections, or the seconds (left) section is missing something.
Its not calling the Mouseover on the left Section. It is calling them on the rght section.

**Comment by runbiscuit** [comment]
Hey there, thanks for the issue - unfortunately while working on this and testing the UI, this was one of the bugs that I've spent ~3 hours trying to debug - but to no avail. Have fiddled around with the Materialize library, but it just doesn't work. Tonight, I'll be pushing a commit to the develop branch, with the updated Materialize and any other dependencies - I'll hope it doesn't break more functionality, and hopefully the tooltip will work for once.

Let's hope it works!

theroyalstudent

**Comment by TheFruF** [comment]
Alright.
I would not want to question your design, but you could just put all Buttons in one section? I dont understand the Materalize lib but maybe the classes should be aligned. So the class name always or never has something between the last color  and "tooltipped".
Thanks for your work!

**Comment by runbiscuit** [comment]
Reworking on it finally - these fixed action buttons will no longer popup to show more options, but will show up as a toolbar. Work in progress.
