### ISSUE TITLE
Forced to refresh the page for newly added to show up?!

### ISSUE THREAD

**Issue by PontusTideman** [theroyalstudent/layered#24]
Hi!

When I add torrents I´m forced to refresh the page to see them, is this normal or not?

**Comment by runbiscuit** [comment]
That isn't normal - you could press on the right arrow to get to the newer torrents - it should be there.
When you have 0 torrents, adding a new torrent would require you to click the right arrow, since it's at the 0th page by default and the torrent object is on the 1st page.

**Comment by runbiscuit** [comment]
Reworking on this, when there's 0 torrents and a new one is added, it would automatically jump onto the first page. Work in progress.
