### ISSUE TITLE
Empty Torrent Spot in the middle

### ISSUE THREAD

**Issue by xF4m3** [theroyalstudent/layered#25]
I added a torrent without supplying a torrent file or a magnet link and now i have an emtpy slot in the middle of all other torrents. I tried that a few times and its definetly reproducable. There is no way of removing those torrents, so a check if a magnetlink or a torrent file is supplied should be implementet if thats not already the case. Also don't mind the diffrent look, I just switched out a few colors more to my liking aswell as a background. Also i added a disply to how large the whole torrent is which normaly doesnt show, i think that would be a good addition. 
Anyway, I think you wrote a awesome webpage nonetheless, so keep up the good work and I saw you are starting to work on this again which i really appreciate. I haven't found any alternative that has good looks aswelll as good functionality.

Here is a screenshot to show what i mean (excuse the bad censorship ;) )

![issue](https://cloud.githubusercontent.com/assets/7432380/22703134/65f6b6fe-ed63-11e6-80e7-1e795edf7bd7.png)

**Comment by runbiscuit** [comment]
Hi there,

Can I ask, how do you "add a torrent without supplying a torrent file or a magnet link"? I'm unsure about that.

Thanks :)

**Comment by xF4m3** [comment]
Well my bad, i encauntered this issue about 3 months ago, I can not remember exactly how i did that :/ I tried it just now with a few diffrent things and ways, but i can not make it happen again. 
I will try to figure it out or remember, but you can close this for now i guess.

Sorry, I should have tried it again before posting (or posted it when i first encaountered it)

**Comment by runbiscuit** [comment]
Closing, do tell me if you ever find the bug again!
