### ISSUE TITLE
Torrent's position in the list glitches when closing the details view.

### ISSUE THREAD

**Issue by zp** [theroyalstudent/layered#6]
Sometimes after closing the 'more details' view on a torrent, the torrent will move to a random spot in the torrent list, until you refresh the entire web ui.
- default listing
  ![](http://i.imgur.com/tgAO1rj.png)
- bringing up details page
  ![](http://i.imgur.com/wntDjAF.png)
- after clicking the x to close details page
  ![](http://i.imgur.com/BEyy3Rq.png)

**Comment by runbiscuit** [comment]
Ah I see, probably a bug with the closing animation.

Thanks for opening this issue - will try to reproduce it on my side later.
Will be opening a wekan board on a roadmap on when these bug fixes will be rolled out!

Do look out for it in README.md soon :)

**Comment by theroyalstudent** [comment]
On roadmap:
https://board.theroyalstudent.com/b/YgLdnHtmskgPZBX5L/layered-roadmap/k2i4oouX57wL7xkaQ

**Comment by runbiscuit** [comment]
Fixed!
