### ISSUE TITLE
Feature Request: Dark theme

### ISSUE THREAD

**Issue by f3bruary** [theroyalstudent/layered#8]
Could you replace the white bg with dark gray (or make it optional) ? A bit easier on the eyes at night...

**Comment by runbiscuit** [comment]
Hey there, that's possible.

I'll change the background to dark grey in the next commit (tomorrow), and after that I would implement a toggle for that :)

Cheers!

**Comment by f3bruary** [comment]
thanks for the quick response !

**Comment by runbiscuit** [comment]
Fixed. Do take a look :)

**Comment by f3bruary** [comment]
broke ui. Can't click any buttons see issue #10
